//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceA")]
    public partial class Response : object
    {
        
        private string ErrorField;
        
        private int ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponsePalabra", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceA")]
    public partial class ResponsePalabra : object
    {
        
        private bool ErrorField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Moviemiento", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceA")]
    public partial class Moviemiento : object
    {
        
        private int IdField;
        
        private string Moviemiento1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moviemiento1
        {
            get
            {
                return this.Moviemiento1Field;
            }
            set
            {
                this.Moviemiento1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Palabra", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceA")]
    public partial class Palabra : object
    {
        
        private int IdField;
        
        private string Palabra1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Palabra1
        {
            get
            {
                return this.Palabra1Field;
            }
            set
            {
                this.Palabra1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSumPar", ReplyAction="http://tempuri.org/IService1/GetSumParResponse")]
        ServiceReference.Response GetSumPar(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSumPar", ReplyAction="http://tempuri.org/IService1/GetSumParResponse")]
        System.Threading.Tasks.Task<ServiceReference.Response> GetSumParAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMoviemiento", ReplyAction="http://tempuri.org/IService1/InsertMoviemientoResponse")]
        string InsertMoviemiento(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMoviemiento", ReplyAction="http://tempuri.org/IService1/InsertMoviemientoResponse")]
        System.Threading.Tasks.Task<string> InsertMoviemientoAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPalabra", ReplyAction="http://tempuri.org/IService1/InsertPalabraResponse")]
        ServiceReference.ResponsePalabra InsertPalabra(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPalabra", ReplyAction="http://tempuri.org/IService1/InsertPalabraResponse")]
        System.Threading.Tasks.Task<ServiceReference.ResponsePalabra> InsertPalabraAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMoviemientos", ReplyAction="http://tempuri.org/IService1/GetMoviemientosResponse")]
        ServiceReference.Moviemiento[] GetMoviemientos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMoviemientos", ReplyAction="http://tempuri.org/IService1/GetMoviemientosResponse")]
        System.Threading.Tasks.Task<ServiceReference.Moviemiento[]> GetMoviemientosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPalabras", ReplyAction="http://tempuri.org/IService1/GetPalabrasResponse")]
        ServiceReference.Palabra[] GetPalabras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPalabras", ReplyAction="http://tempuri.org/IService1/GetPalabrasResponse")]
        System.Threading.Tasks.Task<ServiceReference.Palabra[]> GetPalabrasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPalabraRandm", ReplyAction="http://tempuri.org/IService1/GetPalabraRandmResponse")]
        ServiceReference.Palabra GetPalabraRandm();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPalabraRandm", ReplyAction="http://tempuri.org/IService1/GetPalabraRandmResponse")]
        System.Threading.Tasks.Task<ServiceReference.Palabra> GetPalabraRandmAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : ServiceReference.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference.IService1>, ServiceReference.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference.Response GetSumPar(string value)
        {
            return base.Channel.GetSumPar(value);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Response> GetSumParAsync(string value)
        {
            return base.Channel.GetSumParAsync(value);
        }
        
        public string InsertMoviemiento(string value)
        {
            return base.Channel.InsertMoviemiento(value);
        }
        
        public System.Threading.Tasks.Task<string> InsertMoviemientoAsync(string value)
        {
            return base.Channel.InsertMoviemientoAsync(value);
        }
        
        public ServiceReference.ResponsePalabra InsertPalabra(string value)
        {
            return base.Channel.InsertPalabra(value);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ResponsePalabra> InsertPalabraAsync(string value)
        {
            return base.Channel.InsertPalabraAsync(value);
        }
        
        public ServiceReference.Moviemiento[] GetMoviemientos()
        {
            return base.Channel.GetMoviemientos();
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Moviemiento[]> GetMoviemientosAsync()
        {
            return base.Channel.GetMoviemientosAsync();
        }
        
        public ServiceReference.Palabra[] GetPalabras()
        {
            return base.Channel.GetPalabras();
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Palabra[]> GetPalabrasAsync()
        {
            return base.Channel.GetPalabrasAsync();
        }
        
        public ServiceReference.Palabra GetPalabraRandm()
        {
            return base.Channel.GetPalabraRandm();
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Palabra> GetPalabraRandmAsync()
        {
            return base.Channel.GetPalabraRandmAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:52239/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
